let times={},dateData={},audioOn=false,lastPlayed="";
const P=[["Fajr","Subuh"],["Sunrise","Syuruq"],["Dhuhr","Dzuhur"],["Asr","Ashar"],["Maghrib","Maghrib"],["Isha","Isya"]];
const $=id=>document.getElementById(id);
const isTV=new URLSearchParams(location.search).get("tv")==="1"||window.matchMedia("(min-width:1200px) and (orientation:landscape)").matches;
if(isTV)document.body.classList.add("tv-mode");

async function location(){if(!navigator.geolocation)return load(-7.65,111.37);navigator.geolocation.getCurrentPosition(p=>{load(p.coords.latitude,p.coords.longitude);reverse(p.coords.latitude,p.coords.longitude)},()=>load(-7.65,111.37),{enableHighAccuracy:true,timeout:10000,maximumAge:300000})}
async function reverse(lat,lon){try{let r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}&zoom=12&accept-language=id`),d=await r.json(),a=d.address||{};$( "location").textContent=a.village||a.town||a.city||a.county||"Lokasi Mushola At Taqwa"}catch{$("location").textContent="Mushola At Taqwa"}}
async function load(lat,lon){try{let r=await fetch(`https://api.aladhan.com/v1/timings?latitude=${lat}&longitude=${lon}&method=11`);if(!r.ok)throw 0;let d=await r.json();times=d.data.timings;dateData=d.data.date||{};localStorage.setItem("times",JSON.stringify(times));localStorage.setItem("dateData",JSON.stringify(dateData));$("status").textContent="Online";render()}catch{let c=localStorage.getItem("times");if(c){times=JSON.parse(c);dateData=JSON.parse(localStorage.getItem("dateData")||"{}");$("status").textContent="Offline";render()}else $("status").textContent="Gagal"}}
function render(){let n=new Date(),cur=n.getHours()*60+n.getMinutes(),box=$("prayer-times");box.innerHTML="";P.forEach((x,i)=>{let t=times[x[0]];if(!t)return;let [h,m]=t.split(":").map(Number),active=false;if(x[0]!=="Sunrise"){let prev=P.slice(0,i).reverse().find(y=>y[0]!=="Sunrise"&&times[y[0]]);let next=P.slice(i+1).find(y=>y[0]!=="Sunrise"&&times[y[0]]);let ph=prev?times[prev[0]].split(":").map(Number):null;let nh=next?times[next[0]].split(":").map(Number):null;active=cur>=h*60+m&&( !nh || cur<nh[0]*60+nh[1])}box.innerHTML+=`<div class="prayer-card ${active?"active":""}"><h3>${x[1]}</h3><p>${t}</p><small>${x[0]==="Sunrise"?"Matahari terbit":"Waktu sholat"}</small></div>`})}
function tick(){let n=new Date(),h=String(n.getHours()).padStart(2,"0"),m=String(n.getMinutes()).padStart(2,"0"),s=String(n.getSeconds()).padStart(2,"0");$("clock").textContent=`${h}:${m}:${s}`;$("date").textContent=n.toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});if(dateData.hijri) $("hijri").textContent=`${dateData.hijri.day} ${dateData.hijri.month?.en||""} ${dateData.hijri.year} H`;render();let cur=n.getHours()*60+n.getMinutes()+n.getSeconds()/60,next=null;for(let x of P){if(x[0]==="Sunrise")continue;let q=times[x[0]]?.split(":").map(Number);if(q&&q[0]*60+q[1]>cur){next=[x[1],q[0]*60+q[1]];break}}if(!next&&times.Fajr){let q=times.Fajr.split(":").map(Number);next=["Subuh Esok",1440+q[0]*60+q[1]]}if(next){let d=Math.max(0,next[1]-cur),hh=Math.floor(d/60),mm=Math.floor(d%60),ss=Math.floor((d*60)%60);$("next-label").textContent="MENUJU "+next[0].toUpperCase();$("next").textContent=`${String(hh).padStart(2,"0")}:${String(mm).padStart(2,"0")}:${String(ss).padStart(2,"0")}`}if(audioOn&&!($("night").checked&&(n.getHours()>=22||n.getHours()<4))){for(let x of P.filter(x=>x[0]!=="Sunrise"))if(times[x[0]]===`${h}:${m}`&&lastPlayed!==`${x[0]}-${h}:${m}`){$("adzan").currentTime=0;$("adzan").play().catch(()=>{});lastPlayed=`${x[0]}-${h}:${m}`}}}
$("audio").onclick=()=>{audioOn=true;$("audio").textContent="🔊 Suara Adzan Aktif";$("adzan").play().then(()=>{$("adzan").pause();$("adzan").currentTime=0}).catch(()=>{})};
$("locbtn").onclick=location;$("full").onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();
if(navigator.getBattery)navigator.getBattery().then(b=>{let f=()=>$( "battery").textContent=Math.round(b.level*100)+"%"+(b.charging?" ⚡":"");f();b.onlevelchange=f;b.onchargingchange=f}).catch(()=>{});
setInterval(tick,1000);location();tick();
